# Generated by Django 5.1.4 on 2025-01-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_category_icon_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default='COD', max_length=50),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
