# Generated by Django 5.1.4 on 2025-01-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_orders_payment_method_orderupdate_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.orders'),
        ),
    ]
