# Generated by Django 5.1.4 on 2025-01-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_remove_orders_amountpaid_remove_orders_oid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
